-- Saya, Adi Prasetya, dengan NIM
-- M0521003, bersumpah demi Tuhan YME bahwa saya mengerjakan soal
-- ujian ini berdasarkan hasil pencarian dan pemikiran saya sendiri dan tidak
-- berkonsultasi pada teman lain melalui media apapun. Saya siap menerima sanksi
-- moral apabila saya terbukti melanggar sumpah tersebut"

USE [SPOTIFY];

DROP TABLE IF EXISTS  [STREAM];
DROP TABLE IF EXISTS  [USER];
DROP TABLE IF EXISTS  [SONG_GENRE];
DROP TABLE IF EXISTS  [SONG];
DROP TABLE IF EXISTS  [GENRE];
DROP TABLE IF EXISTS  [ALBUM];
DROP TABLE IF EXISTS  [ARTIST];

-- TABLE ARTIST
CREATE TABLE [ARTIST](
	[ID] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),
	[Name] NVARCHAR(128) NOT NULL
);

CREATE NONCLUSTERED INDEX [NCI_Artist_Name]
ON [ARTIST]([Name]);

-- TABLE ALBUM
CREATE TABLE [ALBUM](
	ID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),
	ArtistID UNIQUEIDENTIFIER NOT NULL,
	Name NVARCHAR(128) NOT NULL,
	ReleaseYear INT NOT NULL,

	CONSTRAINT [FK_ALBUM_ARTIST] FOREIGN KEY ([ArtistID]) REFERENCES [ARTIST]([ID])
);

CREATE NONCLUSTERED INDEX [NCI_Album_Name]
ON [ALBUM]([Name]);


-- TABLE GENRE
CREATE TABLE [GENRE](
	ID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),
	Name NVARCHAR(32) NOT NULL
);

-- TABLE SONG
CREATE TABLE [SONG](
	ID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),
	AlbumID UNIQUEIDENTIFIER NOT NULL,
	Title NVARCHAR(128) NOT NULL,
	Duration INT NOT NULL,
	Duration_Hours INT,
	Duration_Minutes INT,
	Duration_Seconds INT,

	CONSTRAINT [FK_SONG_ALBUM] FOREIGN KEY ([AlbumID]) REFERENCES [ALBUM]([ID])
);

CREATE NONCLUSTERED INDEX [NCI_SONG_Title]
ON [SONG]([Title]);

-- TABLE SONG_GENRE
CREATE TABLE [SONG_GENRE](
	SongID UNIQUEIDENTIFIER NOT NULL, 
	GenreID UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT [PK_SONG_GENRE] PRIMARY KEY ([SongID],[GenreId]),
	CONSTRAINT [FK_SONG_GENRE_SONG] FOREIGN KEY ([SongID]) REFERENCES [SONG]([ID]),
	CONSTRAINT [FK_SONG_GENRE_GENRE] FOREIGN KEY ([GenreID]) REFERENCES [GENRE]([ID])
);

-- TABLE USER
CREATE TABLE [USER](
	ID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),
	Name NVARCHAR(128)
);

CREATE NONCLUSTERED INDEX [NCI_USER_Name]
ON [USER]([Name]);

CREATE TABLE [STREAM](
	ID UNIQUEIDENTIFIER DEFAULT NEWID(),
	UserID UNIQUEIDENTIFIER NOT NULL,
	SongID UNIQUEIDENTIFIER NOT NULL, 
	StartedAt DATETIME NOT NULL,
	FinishedAt DATETIME NOT NULL,
	Duration INT,

	CONSTRAINT [FK_STREAM_USER] FOREIGN KEY ([UserID]) REFERENCES [USER]([ID]),
	CONSTRAINT [FK_STREAM_SONG] FOREIGN KEY ([SongID]) REFERENCES [SONG]([ID])
);